Issue 643 - NoSuchMethodError when using/installing the "Server-Sent Events" add-on (with ZAP 2.1.0)
 - Changed to use the JSON highlighter;
 - Updated the version number;
 - Updated the "changes" element of the ZapAddOn.xml file
 - The build of the new add-on will fix the issue.